version: '3.8'
services:
    apache-env:
        container_name: php-apache
        build: .
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 3000:80
        restart: always

    db:
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
        ports:
            - "9906:3306"
